name: Deploy Fullstack App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend and frontend to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_USER }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y docker.io docker-compose
            sudo systemctl enable docker
            sudo systemctl start docker

            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            cd /home/ubuntu/fullstack-app 

            sudo docker-compose down
            sudo docker system prune -af

            # Actualizar las imágenes desde Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/frontend

            # Levantar contenedores con las imágenes actualizadas
            sudo docker-compose up -d
